#!/usr/bin/env python3
import getpass
import subprocess
from subprocess import PIPE
import platform
import os


def run_command(command):
    subprocess.call(command, shell=True)


def main():
    user = getpass.getuser()
    uid = os.getuid()

    processor = platform.processor()

    if processor == 'arm':
        command = ("docker build "
                    "--build-arg USER_UID={} "
                    "--build-arg USER_NAME={} "
                    "-t lambda-stack .")
    else:
        command = ("docker build "
                    "--build-arg USER_UID={} "
                    "--build-arg USER_NAME={} "
                    "-t lambda-stack .")
    
    run_command(command.format(uid, user))

if __name__ == '__main__':
    main()
